# Generated by Django 4.1.3 on 2022-11-14 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^(?=.*[0-9])(?=.*[A-Z])(?=.*[*.!@$%^&(){}[]:;<>,.?/~_+-=|\\]).{8,20}$', message='Must have at least one upper case alphabate, one digit, and one special character')]),
        ),
    ]
